version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  spring-boot:
    build: ./spring-demo
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - postgres
    mem_limit: 512m
    cpus: 1

  quarkus-jvm:
    build: 
      context: ./quarkus-demo
      dockerfile: Dockerfile.jvm
    ports:
      - "8081:8080"
    environment:
      QUARKUS_PROFILE: docker
    depends_on:
      - postgres
    mem_limit: 512m
    cpus: 1

  # quarkus-native:
  #   build:
  #     context: ./quarkus-demo
  #     dockerfile: Dockerfile.native
  #   ports:
  #     - "8082:8080"
  #   environment:
  #     QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://postgres:5432/testdb
  #     QUARKUS_DATASOURCE_USERNAME: test
  #     QUARKUS_DATASOURCE_PASSWORD: test
  #   depends_on:
  #     - postgres
  #   mem_limit: 512m
  #   cpus: 1

volumes:
  postgres-data:
