FROM maven:3.9-eclipse-temurin-17 AS build
WORKDIR /quarkus-demo
COPY pom.xml .
COPY src ./src
RUN mvn package -DskipTests

FROM eclipse-temurin:17-jre
WORKDIR /app
COPY --from=build /app/target/quarkus-app/ ./
EXPOSE 8080
ENTRYPOINT ["./application"]
